server:
   port: 9001

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: password
    driverClassName: org.h2.Driver
  application:
   name: movie-info-service  
   
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


